end=0
new="data"
while end<10:
    print(" 1 ==>  for create a new data with 1 student in each file")
    print(" 2 ==>  modify existing data")
    print(" 3 ==> delete a particulat student data")
    print(" 4 ==> to view student name present in the file")
    print(" 5 ==> add data to existing file")
    print(" 00 ==> to end the program")
    print(" 6 ==> to show encript options")
    print()
    task=input("Enter the task to do :")
    if task=="1":
        #aa=int(input("Enter the number of students :"))
        a=1
        xx=0
        cv=[]
        for x in range (a):
            print("Student",x+1)
            new="data"
            f=open(new+".txt",'w')
            Name=input("Enter the name :")
            Class=int(input("Enter the Class :"))
            Age=int(input("Enter the Age :"))
            Dob=input("Enter the Date of Birth :")
            BG=input("Enter the Blood Group :")
            He=int(input("Enter the Height :"))
            We=int(input("Enter the Weight :"))
            MH=input("Enter the Medical Health :")
            Gen=input("Enter the Gender :")
            Fn=input("Enter the Father Name :")
            Mn=input("Enter the Mother Name :")
            Fmn=int(input("Enter the Father mobile number :"))
            Mmn=int(input("Enter the Mother mobile number :"))
            Add=input("Enter the Address :")
            print("***************************************")
            print("Name : ",Name)
            print("Class : ",Class)
            print("Age :",Age)
            print("Date Of Birth :",Dob)
            print('Blood group :',BG)
            print('Height :',He)
            print('Weight :',We)
            print('Medical Health :',MH)
            print('Gender :',Gen)
            print('Father Name :',Fn)
            print('Mother Name :',Mn)
            print('Father Mobile Number :', Fmn)
            print('Mother Mobile Number :',Mmn)
            print("Address :",Add)
            print("***************************************")
            print("==> press 0 for no changes")
            print()
            print("==> 1 for change")
            print()
            conf=int(input("Enter the choice : "))
            if conf ==0:
                for x in range(1):
                    export=input("Do u want to export the details in txt format? Y or N : ")
                    if export == "Y":
                        f.write("Name :")
                        f.write(Name)
                        f.write('\n')
                        f.write("Class :")
                        f.write(str(Class))
                        f.write('\n')
                        f.write("Age :")
                        f.write(str(Age))
                        f.write('\n')
                        f.write("Date Of Birth :")
                        f.write(Dob)
                        f.write('\n')
                        f.write("Blood Group :")
                        f.write(BG)
                        f.write('\n')
                        f.write("Height :")
                        f.write(str(He))
                        f.write('\n')
                        f.write("Weight :")
                        f.write(str(We))
                        f.write('\n')
                        f.write("Medical Health :")
                        f.write(MH)
                        f.write('\n')
                        f.write("Gender :")
                        f.write(Gen)
                        f.write('\n')
                        f.write("Father Name :")
                        f.write(Fn)
                        f.write('\n')
                        f.write("Mother Name :")
                        f.write(Mn)
                        f.write('\n')
                        f.write("Father Mobile Number :")
                        f.write(str(Fmn))
                        f.write('\n')
                        f.write("Mother Mobile Number :")
                        f.write(str(Mmn))
                        f.write('\n')
                        f.write("Address :")
                        f.write(Add)
                        f.write('\n')
                        f.close()
                        print("done")
                    elif export == "N":
                        print("ok not exported")
            
            if conf==1:
                mistake=int(input("Enter the no of changes :"))
                for q in range(mistake):
                    a=0
                    print('1  ==> Name')
                    print('2  ==> Class')
                    print('3  ==> Age')
                    print('4  ==> Dob')
                    print('5  ==> Bg')
                    print('6  ==> Height')
                    print('7  ==> Weight')
                    print('8  ==> Medical Health')
                    print('9 ==> Gender')
                    print('10 ==> Father Name')
                    print('11 ==> Mother name')
                    print('12 ==> Father Mobile Number')
                    print('13 ==> mother mobile number')
                    print('14 ==> address')
                    a=input("Enter what to change :")
                    if a=="1":
                        Name=input("Enter the Name :")
                        a=0
                        print("*********************************************")    
                        print("Name : ",Name)
                        print("Class : ",Class)
                        print("Age :",Age)
                        print("Date Of Birth :",Dob)
                        print('Blood group :',BG)
                        print('Height :',He)
                        print('Weight :',We)
                        print('Medical Health :',MH)
                        print('Gender :',Gen)
                        print('Father Name :',Fn)
                        print('Mother Name :',Mn)
                        print('Father Mobile Number :', Fmn)
                        print('Mother Mobile Number :',Mmn)
                        print("Address :",Add)
                        print("*********************************************")
                    elif a=="2":
                        Class=input("Enter the Class :")
                        a=0
                        print("*********************************************")    
                        print("Name : ",Name)
                        print("Class : ",Class)
                        print("Age :",Age)
                        print("Date Of Birth :",Dob)
                        print('Blood group :',BG)
                        print('Height :',He)
                        print('Weight :',We)
                        print('Medical Health :',MH)
                        print('Gender :',Gen)
                        print('Father Name :',Fn)
                        print('Mother Name :',Mn)
                        print('Father Mobile Number :', Fmn)
                        print('Mother Mobile Number :',Mmn)
                        print("Address :",Add)
                        print("*********************************************")
                    elif a=="3":
                        Age=input("Enter the Age :")
                        a=0
                        print("*********************************************")    
                        print("Name : ",Name)
                        print("Class : ",Class)
                        print("Age :",Age)
                        print("Date Of Birth :",Dob)
                        print('Blood group :',BG)
                        print('Height :',He)
                        print('Weight :',We)
                        print('Medical Health :',MH)
                        print('Gender :',Gen)
                        print('Father Name :',Fn)
                        print('Mother Name :',Mn)
                        print('Father Mobile Number :', Fmn)
                        print('Mother Mobile Number :',Mmn)
                        print("Address :",Add)
                        print("*********************************************")
                    elif a=='4':
                        Dob=input("Enter the Date of Birth :")
                        a=0
                        print("*********************************************")    
                        print("Name : ",Name)
                        print("Class : ",Class)
                        print("Age :",Age)
                        print("Date Of Birth :",Dob)
                        print('Blood group :',BG)
                        print('Height :',He)
                        print('Weight :',We)
                        print('Medical Health :',MH)
                        print('Gender :',Gen)
                        print('Father Name :',Fn)
                        print('Mother Name :',Mn)
                        print('Father Mobile Number :', Fmn)
                        print('Mother Mobile Number :',Mmn)
                        print("Address :",Add)
                        print("*********************************************")
                    elif a=='5':
                        BG=input("Enter the Blood Group :")
                        a=0
                        print("*********************************************")    
                        print("Name : ",Name)
                        print("Class : ",Class)
                        print("Age :",Age)
                        print("Date Of Birth :",Dob)
                        print('Blood group :',BG)
                        print('Height :',He)
                        print('Weight :',We)
                        print('Medical Health :',MH)
                        print('Gender :',Gen)
                        print('Father Name :',Fn)
                        print('Mother Name :',Mn)
                        print('Father Mobile Number :', Fmn)
                        print('Mother Mobile Number :',Mmn)
                        print("Address :",Add)
                        print("*********************************************")
                    elif a=='6':
                        He=input("Enter the Height :")
                        a=0
                        print("*********************************************")    
                        print("Name : ",Name)
                        print("Class : ",Class)
                        print("Age :",Age)
                        print("Date Of Birth :",Dob)
                        print('Blood group :',BG)
                        print('Height :',He)
                        print('Weight :',We)
                        print('Medical Health :',MH)
                        print('Gender :',Gen)
                        print('Father Name :',Fn)
                        print('Mother Name :',Mn)
                        print('Father Mobile Number :', Fmn)
                        print('Mother Mobile Number :',Mmn)
                        print("Address :",Add)
                        print("*********************************************")
                    elif a=='7':
                        We =input("Enter the Weight :")
                        a=0
                        print("*********************************************")
                        print("Name : ",Name)
                        print("Class : ",Class)
                        print("Age :",Age)
                        print("Date Of Birth :",Dob)
                        print('Blood group :',BG)
                        print('Height :',He)
                        print('Weight :',We)
                        print('Medical Health :',MH)
                        print('Gender :',Gen)
                        print('Father Name :',Fn)
                        print('Mother Name :',Mn)
                        print('Father Mobile Number :', Fmn)
                        print('Mother Mobile Number :',Mmn)
                        print("Address :",Add)
                        print("*********************************************")
                    elif a== '8':
                        MH=input("Enter the Medical Health :")
                        a=0
                        print("*********************************************")    
                        print("Name : ",Name)
                        print("Class : ",Class)
                        print("Age :",Age)
                        print("Date Of Birth :",Dob)
                        print('Blood group :',BG)
                        print('Height :',He)
                        print('Weight :',We)
                        print('Medical Health :',MH)
                        print('Gender :',Gen)
                        print('Father Name :',Fn)
                        print('Mother Name :',Mn)
                        print('Father Mobile Number :', Fmn)
                        print('Mother Mobile Number :',Mmn)
                        print("Address :",Add)
                        print("*********************************************")
                    elif a=='9':
                        Gen=input("Enter the Gender :")
                        a=0
                        print("*********************************************")    
                        print("Name : ",Name)
                        print("Class : ",Class)
                        print("Age :",Age)
                        print("Date Of Birth :",Dob)
                        print('Blood group :',BG)
                        print('Height :',He)
                        print('Weight :',We)
                        print('Medical Health :',MH)
                        print('Gender :',Gen)
                        print('Father Name :',Fn)
                        print('Mother Name :',Mn)
                        print('Father Mobile Number :', Fmn)
                        print('Mother Mobile Number :',Mmn)
                        print("Address :",Add)
                        print("*********************************************")
                    elif a== '10':
                        Fn=input("Enter the Father name :")
                        a=0
                        print("*********************************************")    
                        print("Name : ",Name)
                        print("Class : ",Class)
                        print("Age :",Age)
                        print("Date Of Birth :",Dob)
                        print('Blood group :',BG)
                        print('Height :',He)
                        print('Weight :',We)
                        print('Medical Health :',MH)
                        print('Gender :',Gen)
                        print('Father Name :',Fn)
                        print('Mother Name :',Mn)
                        print('Father Mobile Number :', Fmn)
                        print('Mother Mobile Number :',Mmn)
                        print("Address :",Add)
                        print("*********************************************")
                    elif a=='11':
                        Mn=input("Enter the Mother name :")
                        a=0
                        print("*********************************************")    
                        print("Name : ",Name)
                        print("Class : ",Class)
                        print("Age :",Age)
                        print("Date Of Birth :",Dob)
                        print('Blood group :',BG)
                        print('Height :',He)
                        print('Weight :',We)
                        print('Medical Health :',MH)
                        print('Gender :',Gen)
                        print('Father Name :',Fn)
                        print('Mother Name :',Mn)
                        print('Father Mobile Number :', Fmn)
                        print('Mother Mobile Number :',Mmn)
                        print("Address :",Add)
                        print("*********************************************")
                    elif a=='12':
                        Fmn=input("Enter the Father mobile number :")
                        a=0
                        print("*********************************************")    
                        print("Name : ",Name)
                        print("Class : ",Class)
                        print("Age :",Age)
                        print("Date Of Birth :",Dob)
                        print('Blood group :',BG)
                        print('Height :',He)
                        print('Weight :',We)
                        print('Medical Health :',MH)
                        print('Gender :',Gen)
                        print('Father Name :',Fn)
                        print('Mother Name :',Mn)
                        print('Father Mobile Number :', Fmn)
                        print('Mother Mobile Number :',Mmn)
                        print("Address :",Add)
                        print("*********************************************")
                    elif a=='13':
                        Mmn=input("Enter the Mother mobile number :")
                        a=0
                        print("*********************************************")    
                        print("Name : ",Name)
                        print("Class : ",Class)
                        print("Age :",Age)
                        print("Date Of Birth :",Dob)
                        print('Blood group :',BG)
                        print('Height :',He)
                        print('Weight :',We)
                        print('Medical Health :',MH)
                        print('Gender :',Gen)
                        print('Father Name :',Fn)
                        print('Mother Name :',Mn)
                        print('Father Mobile Number :', Fmn)
                        print('Mother Mobile Number :',Mmn)
                        print("Address :",Add)
                        print("*********************************************")
                    elif a=='14':
                        Add=input("Enter the Address :")
                        a=0
                        print("*********************************************")    
                        print("Name : ",Name)
                        print("Class : ",Class)
                        print("Age :",Age)
                        print("Date Of Birth :",Dob)
                        print('Blood group :',BG)
                        print('Height :',He)
                        print('Weight :',We)
                        print('Medical Health :',MH)
                        print('Gender :',Gen)
                        print('Father Name :',Fn)
                        print('Mother Name :',Mn)
                        print('Father Mobile Number :', Fmn)
                        print('Mother Mobile Number :',Mmn)
                        print("Address :",Add)
                        print("*********************************************")
                else:
                    break
            
            export=input("Do u want to export the details in txt format? y or n : ")
            if export == "y" or "Y":
                f.write("Name :")
                f.write(Name)
                f.write('\n')
                f.write("Class :")
                f.write(str(Class))
                f.write('\n')
                f.write("Age :")    
                f.write(str(Age))
                f.write('\n')
                f.write("Date Of Birth :")
                f.write(Dob)
                f.write('\n')
                f.write("Blood Group :")
                f.write(BG)
                f.write('\n')
                f.write("Height :")
                f.write(str(He))
                f.write('\n')
                f.write("Weight :")
                f.write(str(We))
                f.write('\n')
                f.write("Medical Health :")
                f.write(MH)
                f.write('\n')
                f.write("Gender :")
                f.write(Gen)
                f.write('\n')
                f.write("Father Name :")
                f.write(Fn)
                f.write('\n')
                f.write("Mother Name :")
                f.write(Mn)
                f.write('\n')
                f.write("Father Mobile Number :")
                f.write(str(Fmn))
                f.write('\n')
                f.write("Mother Mobile Number :")
                f.write(str(Mmn))
                f.write('\n')
                f.write("Address :")
                f.write(Add)
                f.write('\n')
                f.close()
                print("Done")
            else:
                None
    elif task=="2":
        readf=input("Enter the file name to be read :")
        print("====================")
        f=open(readf+'.txt',"r")
        print(f.read())
        f.close()
        f=open(readf+'.txt',"r")
        k=f.readlines()
        print("====================")
        mod=input("Enter the line which is to be modified :")
        for x in range (len(k)):
            k[x]=k[x].strip("\n")
        for a in range(len(k)): 
            if k[a] == mod:
                k[a]=input("enter the change in the line :")
            else:
                None
        f.close()
        f=open(readf+'.txt',"w")
        for send in range (0,len(k)):
            f.write(k[send])
            f.write('\n')
        f.close()
        print("====================")
        print("The data is changed")
        print("====================")
    elif task=="3":
        it=0
        readf=input("Enter the file name to be read :")
        f=open(readf+'.txt',"r")
        print(f.read())
        f.close()
        f=open(readf+'.txt',"r")
        k=f.readlines()
        mod=input("Enter the student which is to be deleted :")
        for d in range (len(k)):
            k[d]=k[d].strip('\n')
        temp=[]
        for x in range(len(k)): 
            if k[x] == mod:
                temp.append(x)
            else:
                None
        if temp[0]<len(k)-1:
            for p in range(temp[0],temp[0]+15):
                k.pop(temp[0])
        print("Done")
        f.close()
        f=open(readf+'.txt',"w")
        for x in range(len(k)):
            f.write(k[x])
            f.write('\n')
        f.close()
        print("The file has been updated.......")
    elif task=="4":
        readf=input("Enter the file name to be read :")
        f=open(readf+'.txt',"r")
        print(f.read())
        f.close()
        f=open(readf+'.txt',"r")
        k=f.readlines()
        print("=================")
        for x in range(len(k)): #strip
            k[x]=k[x].strip("\n")
        for stu in range (0,len(k),15):
            print(k[stu])
        print("=================")
    elif task=="6":
        import collage2
        ru()
        
    elif task =="5":
        aa=int(input("Enter the number of students :"))
        a=0
        cv=[]
        for x in range (0,aa):
            print("Student",x+1)
            f=open(new+".txt",'a')
            Name=input("Enter the name :")
            Class=int(input("Enter the Class :"))
            Age=int(input("Enter the Age :"))
            Dob=input("Enter the Date of Birth :")
            BG=input("Enter the Blood Group :")
            He=int(input("Enter the Height :"))
            We=int(input("Enter the Weight :"))
            MH=input("Enter the Medical Health :")
            Gen=input("Enter the Gender :")
            Fn=input("Enter the Father Name :")
            Mn=input("Enter the Mother Name :")
            Fmn=int(input("Enter the Father mobile number :"))
            Mmn=int(input("Enter the Mother mobile number :"))
            Add=input("Enter the Address :")
            print("***************************************")
            print("Name : ",Name)
            print("Class : ",Class)
            print("Age :",Age)
            print("Date Of Birth :",Dob)
            print('Blood group :',BG)
            print('Height :',He)
            print('Weight :',We)
            print('Medical Health :',MH)
            print('Gender :',Gen)
            print('Father Name :',Fn)
            print('Mother Name :',Mn)
            print('Father Mobile Number :', Fmn)
            print('Mother Mobile Number :',Mmn)
            print("Address :",Add)
            print("***************************************")
            print("==> press 0 for no changes")
            print()
            print("==> 1 for change")
            print()
            conf=int(input("Enter the choice : "))
            if conf ==0:
                for x in range(1):
                    export=input("Do u want to export the details in txt format? Y or N : ")
                    if export == "Y":
                        f.write('\n')
                        f.write("Name :")
                        f.write(Name)
                        f.write('\n')
                        f.write("Class :")
                        f.write(str(Class))
                        f.write('\n')
                        f.write("Age :")
                        f.write(str(Age))
                        f.write('\n')
                        f.write("Date Of Birth :")
                        f.write(Dob)
                        f.write('\n')
                        f.write("Blood Group :")
                        f.write(BG)
                        f.write('\n')
                        f.write("Height :")
                        f.write(str(He))
                        f.write('\n')
                        f.write("Weight :")
                        f.write(str(We))
                        f.write('\n')
                        f.write("Medical Health :")
                        f.write(MH)
                        f.write('\n')
                        f.write("Gender :")
                        f.write(Gen)
                        f.write('\n')
                        f.write("Father Name :")
                        f.write(Fn)
                        f.write('\n')
                        f.write("Mother Name :")
                        f.write(Mn)
                        f.write('\n')
                        f.write("Father Mobile Number :")
                        f.write(str(Fmn))
                        f.write('\n')
                        f.write("Mother Mobile Number :")
                        f.write(str(Mmn))
                        f.write('\n')
                        f.write("Address :")
                        f.write(Add)
                        f.write('\n')
                        f.close()
                        print("done")
                        break
                    elif export == "N":
                        print("ok not exported")
            
            if conf==1:
                mistake=int(input("Enter the no of changes :"))
                for q in range(mistake):
                    a=0
                    print('1  ==> Name')
                    print('2  ==> Class')
                    print('3  ==> Age')
                    print('4  ==> Dob')
                    print('5  ==> Bg')
                    print('6  ==> Height')
                    print('7  ==> Weight')
                    print('8  ==> Medical Health')
                    print('9  ==> Gender')
                    print('10 ==> Father Name')
                    print('11 ==> Mother name')
                    print('12 ==> Father Mobile Number')
                    print('13 ==> mother mobile number')
                    print('14 ==> address')
                    a=input("Enter what to change :")
                    if a=="1":
                        Name=input("Enter the Name :")
                        a=0
                        print("*********************************************")    
                        print("Name : ",Name)
                        print("Class : ",Class)
                        print("Age :",Age)
                        print("Date Of Birth :",Dob)
                        print('Blood group :',BG)
                        print('Height :',He)
                        print('Weight :',We)
                        print('Medical Health :',MH)
                        print('Gender :',Gen)
                        print('Father Name :',Fn)
                        print('Mother Name :',Mn)
                        print('Father Mobile Number :', Fmn)
                        print('Mother Mobile Number :',Mmn)
                        print("Address :",Add)
                        print("*********************************************")
                    elif a=="2":
                        Class=input("Enter the Class :")
                        a=0
                        print("*********************************************")    
                        print("Name : ",Name)
                        print("Class : ",Class)
                        print("Age :",Age)
                        print("Date Of Birth :",Dob)
                        print('Blood group :',BG)
                        print('Height :',He)
                        print('Weight :',We)
                        print('Medical Health :',MH)
                        print('Gender :',Gen)
                        print('Father Name :',Fn)
                        print('Mother Name :',Mn)
                        print('Father Mobile Number :', Fmn)
                        print('Mother Mobile Number :',Mmn)
                        print("Address :",Add)
                        print("*********************************************")
                    elif a=="3":
                        Age=input("Enter the Age :")
                        a=0
                        print("*********************************************")    
                        print("Name : ",Name)
                        print("Class : ",Class)
                        print("Age :",Age)
                        print("Date Of Birth :",Dob)
                        print('Blood group :',BG)
                        print('Height :',He)
                        print('Weight :',We)
                        print('Medical Health :',MH)
                        print('Gender :',Gen)
                        print('Father Name :',Fn)
                        print('Mother Name :',Mn)
                        print('Father Mobile Number :', Fmn)
                        print('Mother Mobile Number :',Mmn)
                        print("Address :",Add)
                        print("*********************************************")
                    elif a=='4':
                        Dob=input("Enter the Date of Birth :")
                        a=0
                        print("*********************************************")    
                        print("Name : ",Name)
                        print("Class : ",Class)
                        print("Age :",Age)
                        print("Date Of Birth :",Dob)
                        print('Blood group :',BG)
                        print('Height :',He)
                        print('Weight :',We)
                        print('Medical Health :',MH)
                        print('Gender :',Gen)
                        print('Father Name :',Fn)
                        print('Mother Name :',Mn)
                        print('Father Mobile Number :', Fmn)
                        print('Mother Mobile Number :',Mmn)
                        print("Address :",Add)
                        print("*********************************************")
                    elif a=='5':
                        BG=input("Enter the Blood Group :")
                        a=0
                        print("*********************************************")    
                        print("Name : ",Name)
                        print("Class : ",Class)
                        print("Age :",Age)
                        print("Date Of Birth :",Dob)
                        print('Blood group :',BG)
                        print('Height :',He)
                        print('Weight :',We)
                        print('Medical Health :',MH)
                        print('Gender :',Gen)
                        print('Father Name :',Fn)
                        print('Mother Name :',Mn)
                        print('Father Mobile Number :', Fmn)
                        print('Mother Mobile Number :',Mmn)
                        print("Address :",Add)
                        print("*********************************************")
                    elif a=='6':
                        He=input("Enter the Height :")
                        a=0
                        print("*********************************************")    
                        print("Name : ",Name)
                        print("Class : ",Class)
                        print("Age :",Age)
                        print("Date Of Birth :",Dob)
                        print('Blood group :',BG)
                        print('Height :',He)
                        print('Weight :',We)
                        print('Medical Health :',MH)
                        print('Gender :',Gen)
                        print('Father Name :',Fn)
                        print('Mother Name :',Mn)
                        print('Father Mobile Number :', Fmn)
                        print('Mother Mobile Number :',Mmn)
                        print("Address :",Add)
                        print("*********************************************")
                    elif a=='7':
                        We =input("Enter the Weight :")
                        a=0
                        print("*********************************************")
                        print("Name : ",Name)
                        print("Class : ",Class)
                        print("Age :",Age)
                        print("Date Of Birth :",Dob)
                        print('Blood group :',BG)
                        print('Height :',He)
                        print('Weight :',We)
                        print('Medical Health :',MH)
                        print('Gender :',Gen)
                        print('Father Name :',Fn)
                        print('Mother Name :',Mn)
                        print('Father Mobile Number :', Fmn)
                        print('Mother Mobile Number :',Mmn)
                        print("Address :",Add)
                        print("*********************************************")
                    elif a== '8':
                        MH=input("Enter the Medical Health :")
                        a=0
                        print("*********************************************")    
                        print("Name : ",Name)
                        print("Class : ",Class)
                        print("Age :",Age)
                        print("Date Of Birth :",Dob)
                        print('Blood group :',BG)
                        print('Height :',He)
                        print('Weight :',We)
                        print('Medical Health :',MH)
                        print('Gender :',Gen)
                        print('Father Name :',Fn)
                        print('Mother Name :',Mn)
                        print('Father Mobile Number :', Fmn)
                        print('Mother Mobile Number :',Mmn)
                        print("Address :",Add)
                        print("*********************************************")
                    elif a=='9':
                        Gen=input("Enter the Gender :")
                        a=0
                        print("*********************************************")    
                        print("Name : ",Name)
                        print("Class : ",Class)
                        print("Age :",Age)
                        print("Date Of Birth :",Dob)
                        print('Blood group :',BG)
                        print('Height :',He)
                        print('Weight :',We)
                        print('Medical Health :',MH)
                        print('Gender :',Gen)
                        print('Father Name :',Fn)
                        print('Mother Name :',Mn)
                        print('Father Mobile Number :', Fmn)
                        print('Mother Mobile Number :',Mmn)
                        print("Address :",Add)
                        print("*********************************************")
                    elif a== '10':
                        Fn=input("Enter the Father name :")
                        a=0
                        print("*********************************************")    
                        print("Name : ",Name)
                        print("Class : ",Class)
                        print("Age :",Age)
                        print("Date Of Birth :",Dob)
                        print('Blood group :',BG)
                        print('Height :',He)
                        print('Weight :',We)
                        print('Medical Health :',MH)
                        print('Gender :',Gen)
                        print('Father Name :',Fn)
                        print('Mother Name :',Mn)
                        print('Father Mobile Number :', Fmn)
                        print('Mother Mobile Number :',Mmn)
                        print("Address :",Add)
                        print("*********************************************")
                    elif a=='11':
                        Mn=input("Enter the Mother name :")
                        a=0
                        print("*********************************************")    
                        print("Name : ",Name)
                        print("Class : ",Class)
                        print("Age :",Age)
                        print("Date Of Birth :",Dob)
                        print('Blood group :',BG)
                        print('Height :',He)
                        print('Weight :',We)
                        print('Medical Health :',MH)
                        print('Gender :',Gen)
                        print('Father Name :',Fn)
                        print('Mother Name :',Mn)
                        print('Father Mobile Number :', Fmn)
                        print('Mother Mobile Number :',Mmn)
                        print("Address :",Add)
                        print("*********************************************")
                    elif a=='12':
                        Fmn=input("Enter the Father mobile number :")
                        a=0
                        print("*********************************************")    
                        print("Name : ",Name)
                        print("Class : ",Class)
                        print("Age :",Age)
                        print("Date Of Birth :",Dob)
                        print('Blood group :',BG)
                        print('Height :',He)
                        print('Weight :',We)
                        print('Medical Health :',MH)
                        print('Gender :',Gen)
                        print('Father Name :',Fn)
                        print('Mother Name :',Mn)
                        print('Father Mobile Number :', Fmn)
                        print('Mother Mobile Number :',Mmn)
                        print("Address :",Add)
                        print("*********************************************")
                    elif a=='13':
                        Mmn=input("Enter the Mother mobile number :")
                        a=0
                        print("*********************************************")    
                        print("Name : ",Name)
                        print("Class : ",Class)
                        print("Age :",Age)
                        print("Date Of Birth :",Dob)
                        print('Blood group :',BG)
                        print('Height :',He)
                        print('Weight :',We)
                        print('Medical Health :',MH)
                        print('Gender :',Gen)
                        print('Father Name :',Fn)
                        print('Mother Name :',Mn)
                        print('Father Mobile Number :', Fmn)
                        print('Mother Mobile Number :',Mmn)
                        print("Address :",Add)
                        print("*********************************************")
                    elif a=='14':
                        Add=input("Enter the Address :")
                        a=0
                        print("*********************************************")    
                        print("Name : ",Name)
                        print("Class : ",Class)
                        print("Age :",Age)
                        print("Date Of Birth :",Dob)
                        print('Blood group :',BG)
                        print('Height :',He)
                        print('Weight :',We)
                        print('Medical Health :',MH)
                        print('Gender :',Gen)
                        print('Father Name :',Fn)
                        print('Mother Name :',Mn)
                        print('Father Mobile Number :', Fmn)
                        print('Mother Mobile Number :',Mmn)
                        print("Address :",Add)
                        print("*********************************************")
                    else:
                        break
            
            export=input("Do u want to export the details in txt format? y or n : ")
            if export == "y" or "Y":
                f.write('\n')
                f.write("Name :")
                f.write(Name)
                f.write('\n')
                f.write("Class :")
                f.write(str(Class))
                f.write('\n')
                f.write("Age :")    
                f.write(str(Age))
                f.write('\n')
                f.write("Date Of Birth :")
                f.write(Dob)
                f.write('\n')
                f.write("Blood Group :")
                f.write(BG)
                f.write('\n')
                f.write("Height :")
                f.write(str(He))
                f.write('\n')
                f.write("Weight :")
                f.write(str(We))
                f.write('\n')
                f.write("Medical Health :")
                f.write(MH)
                f.write('\n')
                f.write("Gender :")
                f.write(Gen)
                f.write('\n')
                f.write("Father Name :")
                f.write(Fn)
                f.write('\n')
                f.write("Mother Name :")
                f.write(Mn)
                f.write('\n')
                f.write("Father Mobile Number :")
                f.write(str(Fmn))
                f.write('\n')
                f.write("Mother Mobile Number :")
                f.write(str(Mmn))
                f.write('\n')
                f.write("Address :")
                f.write(Add)
                f.write('\n')
                f.close()
                print("Done")
            else:
                None
    elif task=="00":
        end+=10000
        print("Program Ended")
        gg=input("press any button and enter to end")

